# Configurações de build para a Netlify
[build]
  # Comando para construir o site
  command = "yarn build"
  # Pasta onde o site construído será publicado
  publish = "dist"

# Regra de redirecionamento para Single Page Applications (SPA)
# Isso garante que o React Router funcione corretamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
